sudo: required

services:
  - docker

before_install:
  - docker build -t choijong/nolonglinks .

script:
  - docker run choijong/nolonglinks python manage.py runserver 8000

after_success:
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push choijong/nolonglinks