sudo: required

language: python
python:
    - "3.8"

services:
  - docker

script:
  - echo "no script!"

after_success:
  - pip install awscli
  # configuration
  # https://stackoverflow.com/questions/34689445/cant-push-image-to-amazon-ecr-fails-with-no-basic-auth-credentials
  # https://stackoverflow.com/questions/60583847/aws-ecr-saying-cannot-perform-an-interactive-login-from-a-non-tty-device-after
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws configure set region ap-northeast-2

  # build and push to ecr
  - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com
  - docker build -t nolonglinks .
  - docker tag nolonglinks:latest 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com/nolonglinks:latest
  - docker push 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com/nolonglinks:latest

  # push to ecs
  - ecs update nolonglinks-task
  - task=$(aws ecs list-tasks --cluster nolonglinks-cluster --desired-status RUNNING --family nolonglinks-task | egrep "task/" | sed -E "s/.*task\/(.*)\"/\1/")
  # - echo "$task"
  - aws ecs stop-task --cluster nolonglinks-cluster --task "$task"
  - aws ecs update-service --cluster nolonglinks-cluster --service my-service --task-definition nolonglinks-task --force-new-deployment
