sudo: required

services:
  - docker

before_install:
  - docker build -t choijong/nolonglinks .

script:
  - docker run -dp 8000:8000 choijong/nolonglinks 
  
after_success:
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push choijong/nolonglinks