sudo: required

services:
  - docker

before_install:
  - docker build -t yoonchoi67/nolonglinks .

script:
  - docker run -dp 8000:8000 yoonchoi67/nolonglinks 

after_success:
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push yoonchoi67/nolonglinks