sudo: required

services:
  - docker

before_install:
  # - docker build -t yoonchoi67/nolonglinks ./django-webapp
  # - docker build -t yoonchoi67/nginx ./nginx
script:
  - docker run -dp 8000:8000 yoonchoi67/nolonglinks 

after_success:
  # - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  # - docker push yoonchoi67/nolonglinks
  # - docker push yoonchoi67/nginx
  
  # push to ecr
  - pip install --user awscli
  - pip install ecs-deploy==1.12.0
  - pip install ordered_dict
  # configuration
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws configure set region ap-northeast-2
  # 
  # https://stackoverflow.com/questions/60583847/aws-ecr-saying-cannot-perform-an-interactive-login-from-a-non-tty-device-after
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - aws ecr get-login-password --region ap-northeast-2 | docker login -u AWS --password-stdin 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com
  - docker login -u AWS -p $(aws ecr get-login-password --region ap-northeast-2) --password-stdin 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com
  # - aws ecr get-login-password --region ap-northeast-2 
  # - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com


  # - docker build -t yoonchoi67/nolonglinks ./django-webapp
  - docker build -t nolonglinks ./django-webapp
  
  # - docker tag yoonchoi67/nolonglinks:latest 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com/nolonglinks:latest
  - docker tag nolonglinks:latest 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com/nolonglinks:latest
  - docker push 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com/nolonglinks:latest

  # push to ecs
  # - ecs deploy url-shortener-cluster service-name --image nolonglinks-task-definition:4 yoonchoi67/nolonglinks
  - ecs deploy url-shortener-cluster service-name --task nolonglinks #--image nolonglinks-task-definition:4 yoonchoi67/nolonglinks

  # deploy:
#   provider: script
#   # specify the deployment script
#     script: bash deploy.sh
#     # specify to deploy with code change a given branch
#     on:
#       branch: master

# deploy:
#   provider: elasticbeanstalk
#   region: ap-northeast-2
#   app: nolonglinks
#   env: Nolonglinks-env-1
#   bucket_name: nolonglinks-bucket-name
#   bucket_path: nolonglinks
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY