sudo: required

services:
  - docker

before_install:
  - docker build -t yoonchoi67/nolonglinks ./django-webapp
  # - docker build -t yoonchoi67/nginx ./nginx

script:
  - docker run -dp 8000:8000 yoonchoi67/nolonglinks 

after_success:
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yoonchoi67/nolonglinks
  # - docker push yoonchoi67/nginx
  
  # push to ecr
  - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com
  - docker tag nolonglinks:latest 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com/nolonglinks:latest
  - docker push 388250753725.dkr.ecr.ap-northeast-2.amazonaws.com/nolonglinks:latest

  # push to ecs
  ecs deploy url-shortener-cluster service-name --image nolonglinks-task-definition:4 yoonchoi67/nolonglinks

  # deploy:
#   provider: script
#   # specify the deployment script
#     script: bash deploy.sh
#     # specify to deploy with code change a given branch
#     on:
#       branch: master

# deploy:
#   provider: elasticbeanstalk
#   region: ap-northeast-2
#   app: nolonglinks
#   env: Nolonglinks-env-1
#   bucket_name: nolonglinks-bucket-name
#   bucket_path: nolonglinks
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY